sculpin:
sculpin_theme:
    theme: sculpin/bootstrap-3-blog-theme
sculpin_content_types:

    posts:
        permalink: docs/changelog/:year/:month/
        path: _changelog
        enabled: true

    terminuspages:
        singular_name: terminuspage
        permalink: docs/terminus/:basename/
        path: docs/_terminuspages
        layout: terminuspage

    docs:
        type: path
        path: _docs
        singular_name: doc
        enabled: true
        taxonomies:
            - categories
            - tags
            - contributors
        permalink: docs/:basename/

    guides:
        type: meta
        taxonomies:
            - categories
            - tags
            - contributors
        permalink: docs/guides/:basename/
